### ISSUE TITLE
您好，麻烦问下，每屏幕显示一个半，到最后一个继续按照之前的显示该怎么调，谢谢

### ISSUE THREAD

**Issue by thundeGG** [zhimaochen/SnapHelperDemo#2]

**Comment by zhimaochen** [comment]
你的意思最后一个Item不作特殊处理，继续按照对齐第一个Item左边缘的规则来显示？如果是这样的话就去掉对最后一个Item的特殊判断就可以了，我文章里有提到。但是这样的处理的方式可能会导致最后一个Item永远无法显示完整，你确定要这样做？

**Comment by thundeGG** [comment]
是的，感谢您的回复，我加了一个空的item，到达了显示的效果
